# compose.yml
services:
    yt:
        build: 
            context: .
            dockerfile: Dockerfile
        image: test_inference:latest
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            - DISPLAY=:0
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
            - DEBUG_COLORS=1
            - TERM=xterm-256color
            - COLORTERM=truecolor
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./app.py:/app/app.py
            # para rodar inferencia simples:
            #- ./inferencia_simples.py:/app/inferencia_simples.py
        stdin_open: true  # entrada interativa
        tty: true